<a href="https://colab.research.google.com/github/Bintangnazwar/-1023---Drought---Jawaban-/blob/main/CODELEB_MODUL_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

COBELEB 1

a. Buat 12 tuple (masing-masing 4 data: int, float, string acak)

In [1]:
data_tuple = [
    (1, 2.5, "apel", 10),
    (3.2, 7, "mangga", 5),
    ("jeruk", 8, 4.5, 2),
    (9, "pisang", 6.7, 3),
    (4, 1.1, "melon", 8),
    ("anggur", 2, 3.3, 6),
    (5, "kiwi", 9.9, 1),
    (7.7, 4, "leci", 12),
    (11, "durian", 2.2, 14),
    (13, 6.6, "salak", 15),
    ("nanas", 16, 8.8, 17),
    (18, "pepaya", 3.4, 19)
]

b. Konversi tuple ke daftar (list)

In [2]:
data_list = []

for tup in data_tuple:
    for item in tup:
        data_list.append(item)

print(data_list)

[1, 2.5, 'apel', 10, 3.2, 7, 'mangga', 5, 'jeruk', 8, 4.5, 2, 9, 'pisang', 6.7, 3, 4, 1.1, 'melon', 8, 'anggur', 2, 3.3, 6, 5, 'kiwi', 9.9, 1, 7.7, 4, 'leci', 12, 11, 'durian', 2.2, 14, 13, 6.6, 'salak', 15, 'nanas', 16, 8.8, 17, 18, 'pepaya', 3.4, 19]


c. Tambahkan 2 data baru pada indeks sesuai digit terakhir NIM

In [4]:
nim_terakhir = 3

data_list.insert(nim_terakhir, "DATA_BARU_1")
data_list.insert(nim_terakhir + 1, "DATA_BARU_2")

print(data_list)

[1, 2.5, 'apel', 'DATA_BARU_1', 'DATA_BARU_2', 10, 3.2, 7, 'mangga', 5, 'jeruk', 8, 4.5, 2, 9, 'pisang', 6.7, 3, 4, 1.1, 'melon', 8, 'anggur', 2, 3.3, 6, 5, 'kiwi', 9.9, 1, 7.7, 4, 'leci', 12, 11, 'durian', 2.2, 14, 13, 6.6, 'salak', 15, 'nanas', 16, 8.8, 17, 18, 'pepaya', 3.4, 19]


d. Hapus tipe data float dari daftar

In [5]:
data_list = [x for x in data_list if not isinstance(x, float)]

print(data_list)

[1, 'apel', 'DATA_BARU_1', 'DATA_BARU_2', 10, 7, 'mangga', 5, 'jeruk', 8, 2, 9, 'pisang', 3, 4, 'melon', 8, 'anggur', 2, 6, 5, 'kiwi', 1, 4, 'leci', 12, 11, 'durian', 14, 13, 'salak', 15, 'nanas', 16, 17, 18, 'pepaya', 19]


e. Urutkan dalam urutan menurun

In [6]:
data_list = sorted(data_list, key=lambda x: str(x), reverse=True)

print(data_list)

['salak', 'pisang', 'pepaya', 'nanas', 'melon', 'mangga', 'leci', 'kiwi', 'jeruk', 'durian', 'apel', 'anggur', 'DATA_BARU_2', 'DATA_BARU_1', 9, 8, 8, 7, 6, 5, 5, 4, 4, 3, 2, 2, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 1, 1]


CODELEB 2

a. Buat array 2D

In [8]:
import numpy as np

nim = "202310370311063"
# Ambil 6 digit terakhir
last_6 = nim[-6:]
# Ubah ke list integer
nim_digits = [int(x) for x in last_6]
# Buat matriks 2x3
matrix = np.array(nim_digits).reshape(2, 3)

print("Matriks 2D:")
print(matrix)

Matriks 2D:
[[3 1 1]
 [0 6 3]]


b. Operasi Matriks

In [9]:
# Tambah
print("Penjumlahan:")
print(matrix + matrix)

# Kurang
print("Pengurangan:")
print(matrix - matrix)

# Kali
print("Perkalian:")
print(matrix * matrix)

Penjumlahan:
[[ 6  2  2]
 [ 0 12  6]]
Pengurangan:
[[0 0 0]
 [0 0 0]]
Perkalian:
[[ 9  1  1]
 [ 0 36  9]]


c. Konversi ke 1D

In [10]:
matrix_1d = matrix.flatten()

print(matrix_1d)

[3 1 1 0 6 3]


d. Pengirisian

In [11]:
print("Baris pertama:", matrix[0])
print("Kolom kedua:", matrix[:, 1])
print("Elemen tengah:", matrix[0, 1])

Baris pertama: [3 1 1]
Kolom kedua: [1 6]
Elemen tengah: 1


CODELEB 3

a. Buat Series berisi kamus


In [12]:
import pandas as pd

produk = {
    "Produk A": 101,
    "Produk B": 102,
    "Produk C": 103
}

series_produk = pd.Series(produk)

print(series_produk)

Produk A    101
Produk B    102
Produk C    103
dtype: int64


b. Buat DataFrame (4 kolom, 5 data)


In [13]:
data = {
    "Nama": ["Andi", "Budi", "Citra", "Dewi", "Eka"],
    "Umur": [20, 21, 19, 22, 20],
    "Jurusan": ["TI", "SI", "MI", "TI", "SI"],
    "Nilai": [85, 90, 88, 92, 87]
}

df = pd.DataFrame(data)

print(df)


    Nama  Umur Jurusan  Nilai
0   Andi    20      TI     85
1   Budi    21      SI     90
2  Citra    19      MI     88
3   Dewi    22      TI     92
4    Eka    20      SI     87


c. Tambah 1 kolom baru

In [14]:
df["Status"] = ["Lulus", "Lulus", "Lulus", "Lulus", "Lulus"]

print(df)

    Nama  Umur Jurusan  Nilai Status
0   Andi    20      TI     85  Lulus
1   Budi    21      SI     90  Lulus
2  Citra    19      MI     88  Lulus
3   Dewi    22      TI     92  Lulus
4    Eka    20      SI     87  Lulus


d. Urutkan berdasarkan Nama (alfabet)

In [15]:
df_sorted = df.sort_values(by="Nama")

print(df_sorted)

    Nama  Umur Jurusan  Nilai Status
0   Andi    20      TI     85  Lulus
1   Budi    21      SI     90  Lulus
2  Citra    19      MI     88  Lulus
3   Dewi    22      TI     92  Lulus
4    Eka    20      SI     87  Lulus
